[tool.poetry]
name = "movie-ratings-streaming"
version = "0.1.1"
description = "Spark Structured Streaming + Kafka demo app"
authors = ["Guido Kosloff Gancedo <guidokosloff@gmail.com>"]
readme = "README.md"
packages = [{include = "movie_ratings_streaming"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry.group.dev.dependencies]
pyspark = "3.3.2"
delta-spark = "^2.2.0"
black = "^23.1.0"
isort = "^5.12.0"
confluent-kafka = "^2.0.2"
requests = "^2.28.2"
fastavro = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
